
modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="configurable_recipes"
version="1.0.0"
displayName="Configurable Recipes"
logoFile="configurable_recipes.png"
credits="Nautilus Shell Block texture and concept by u/STARRYSOCK"
authors="spacegoat3"
description='''
Adds new recipes to the game. Those recipes can be enabled/disabled trough config.
'''

[[dependencies.configurable_recipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.17.1,1.18,1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
